modLoader="javafml"
loaderVersion="[2,)"
license="GPL-3.0-only"
issueTrackerURL="https://github.com/xfl03/MCCustomSkinLoader/issues"
[[mods]]
modId="customskinloader"
version="${modFullVersion}"
displayName="CustomSkinLoader"
authors="xfl03, JLChnToZ, ZekerZhayard"
displayTest="IGNORE_ALL_VERSION"
description='''
Custom Skin Loader for Minecraft
'''

# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
#[[mixins]]
#config="{mod_id}.mixins.json"

# The [[accessTransformers]] block allows you to declare where your AT file is.
# If this block is omitted, a fallback attempt will be made to load an AT from META-INF/accesstransformer.cfg
#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

# The coremods config file path is not configurable and is always loaded from META-INF/coremods.json

[[dependencies.customskinloader]]
modId="neoforge"
type="required"
versionRange="[20.5,)"
ordering="NONE"
side="CLIENT"
[[dependencies.customskinloader]]
modId="minecraft"
type="required"
versionRange="[1.20.5,)"
ordering="NONE"
side="BOTH"
